### ISSUE TITLE
Rez with persistent interference pattern.

### ISSUE THREAD

**Issue by skmp** [reicast/gamedb#102]
_From @Reznaut on December 28, 2016 1:54_

Rez on reicast has the graphical glitch below. Happens with gdi and cdi PAL game images. Happens on LG G4 and also in an old Samsung Epic Galaxy S. Also happened on a TUVVA android tablet. Anyone else with the same issue or a fix? 

The interference pattern is always there and does not move. It does not affect the lateral edges on widescreen, the flying dude, or the bad guys.

Running : reicast-android-debug-aca9cb6

![capture _2016-12-27-20-47-58](https://cloud.githubusercontent.com/assets/9502674/21512027/33af0646-cc76-11e6-91b5-032758f9d818.png)

_Copied from original issue: reicast/reicast-emulator#995_

**Comment by skmp** [comment]
Is this still an issue with the latest beta from #1208? Also should be moved to gamedb

**Comment by Reznaut** [comment]
Still an issue with the stable release available at the google playstore on 9/11/2018.

**Comment by Reznaut** [comment]
This is a defining dreamcast game still exemplary 20 years post release. Is this bug being worked on or has it been resolved in the latest beta release?

**Comment by skmp** [comment]
This caused by a disabled feature. I think, in newer beta versions the RTT feature is enabled by default, which should fix this (and other) games. r8 should be out later today, would be great if you can re-test with it

**Comment by Reznaut** [comment]
Problem still present with the stable release on google playstore today 9/12/2018. Tested on LG G4.

What is RTT? How do I switch it on or off in the settings? Thank you.

**Comment by BanditTech** [comment]
Rez is the only reason I set up this emulator! Really trying to figure out this bug with the visual glitches. How do you get the beta release

**Comment by baka0815** [comment]
Visit reicast.com and go to the download section or go directly to https://builds.reicast.com

**Comment by BanditTech** [comment]
I signed up for beta tester and loaded up the freshest 1. it still has the same visual glitches it has artifacting going across the center of the screen in three lines

**Comment by BanditTech** [comment]
Maybe some setting I can toggle? I have been trying all sorry of stuff to fix it

**Comment by Reznaut** [comment]
Samsung S9 also has the same issue. Using the stable release on google playstore 5/2/2019.

**Comment by flyinghead** [comment]
Try the beta: install the first APK at http://builds.reicast.com/
